# Thư viện

In [2]:
import torch
import random

## Bài 1. Tạo Tensor cơ bản 

In [3]:

a = torch.tensor( 
[[1, 2, 3], 
[4, 5, 6]], 
dtype=torch.int32 
) 
print(a) 

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


## Bài 2. Tạo các Tensor thường dùng

In [4]:
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)
g= torch.full((5,5),10)
print (g)

tensor([[0.8341, 0.1901, 0.3973, 0.2348],
        [0.1846, 0.3784, 0.1083, 0.7714],
        [0.9009, 0.7451, 0.9067, 0.2322]])
tensor([[-1.8390,  0.0765,  0.0795, -0.1820],
        [-0.1652,  0.1883,  1.5230,  1.0537],
        [ 0.0894, -0.1540, -0.8897,  1.0639]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


## Bài 3.Kiểm tra thông tin Tensor

In [5]:
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


## Bài 4. Slicing và Indexing

In [6]:

import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])
print("\nTensor a[1:, 2:4]:")
print("\n lấy hai phần tử cuối cùng trên chiều thứ ba")
print(a[:,:,-2])

Original tensor:
tensor([[[-0.0082, -1.2159, -0.9523,  0.1514, -1.7428],
         [-2.2349, -0.1484, -0.4028, -0.7674, -0.5039],
         [-0.2759,  1.3838, -0.1757, -1.0712,  1.6831],
         [-1.3377,  1.1225,  1.0401, -0.3537, -0.2697]],

        [[ 1.1588,  0.5482,  1.4108, -0.5199, -0.3052],
         [ 0.5447,  1.1307, -0.3367, -0.0240,  0.8067],
         [ 1.3442,  0.4690, -1.6673, -0.2420,  2.8248],
         [ 0.3837,  1.1012, -0.9902,  2.2013, -0.5040]],

        [[ 0.7812, -0.7972, -1.7154, -0.9148,  1.4662],
         [-0.4042,  1.0456,  0.1561, -0.0172,  0.2334],
         [ 0.3257,  0.7929,  1.4197, -0.5740, -0.6518],
         [ 0.0347,  1.0849, -1.5772, -0.2547, -0.3460]]])

Tensor a[1]:
tensor([[ 1.1588,  0.5482,  1.4108, -0.5199, -0.3052],
        [ 0.5447,  1.1307, -0.3367, -0.0240,  0.8067],
        [ 1.3442,  0.4690, -1.6673, -0.2420,  2.8248],
        [ 0.3837,  1.1012, -0.9902,  2.2013, -0.5040]])

Tensor a[1:, 2:4]:
tensor([[[ 1.3442,  0.4690, -1.6673, -0.2420,  2.8

## Bài 5. Reshape và Flatten

In [7]:
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))
print("\nReshape 2 x 6:")
print(a.reshape( 2,6))

Original:
tensor([[-0.8208, -0.3704, -0.2286,  0.0915],
        [ 0.1304,  0.7544, -0.6764,  2.6257],
        [-0.3247, -0.4819,  0.9625, -2.0347]])

Flatten:
tensor([-0.8208, -0.3704, -0.2286,  0.0915,  0.1304,  0.7544, -0.6764,  2.6257,
        -0.3247, -0.4819,  0.9625, -2.0347])

Reshape to 3 x 2 x 2:
tensor([[[-0.8208, -0.3704],
         [-0.2286,  0.0915]],

        [[ 0.1304,  0.7544],
         [-0.6764,  2.6257]],

        [[-0.3247, -0.4819],
         [ 0.9625, -2.0347]]])

Reshape 2 x 6:
tensor([[-0.8208, -0.3704, -0.2286,  0.0915,  0.1304,  0.7544],
        [-0.6764,  2.6257, -0.3247, -0.4819,  0.9625, -2.0347]])


## Bài 6. Phép toán và nhân ma trận

In [8]:
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\na*b:")
print(a *b)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 2.3049,  0.3793, -1.4353],
        [-0.6407, -1.4454, -1.2776]])
b:
tensor([[-0.4983,  0.2017, -0.9823],
        [-1.5473,  0.0530,  0.6142]])

a + b:
tensor([[ 1.8066,  0.5809, -2.4176],
        [-2.1880, -1.3924, -0.6634]])

a / b:
tensor([[ -4.6259,   1.8805,   1.4612],
        [  0.4141, -27.2526,  -2.0800]])

a^2:
tensor([[5.3125, 0.1438, 2.0601],
        [0.4105, 2.0893, 1.6322]])

a*b:
tensor([[-1.1484,  0.0765,  1.4099],
        [ 0.9914, -0.0767, -0.7847]])

Matrix multiplication:
tensor([[ 0.3380, -4.4278],
        [ 1.2827,  0.1300]])


## Bài 7. Các hàm thống kê trên Tensor

In [9]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))
print("\n thay bang dim=1:")
print(torch.mean(a, dim=1))
print("\nStandard deviation:")
print(torch.std(a, dim=1))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[-0.2403,  0.2461, -1.2799, -0.7830],
        [ 0.2613, -1.0102, -0.2369,  1.5885],
        [ 0.3047, -0.7934, -0.5647,  0.7243]])

Mean:
tensor([ 0.1086, -0.5192, -0.6938,  0.5099])

Standard deviation:
tensor([0.3029, 0.6715, 0.5334, 1.2002])

Cumulative sum:
tensor([[-0.2403,  0.2461, -1.2799, -0.7830],
        [ 0.0210, -0.7642, -1.5168,  0.8054],
        [ 0.3258, -1.5576, -2.0815,  1.5297]])

 thay bang dim=1:
tensor([-0.5143,  0.1507, -0.0823])

Standard deviation:
tensor([0.6612, 1.0920, 0.7162])

Cumulative sum:
tensor([[-0.2403,  0.0058, -1.2742, -2.0572],
        [ 0.2613, -0.7489, -0.9858,  0.6027],
        [ 0.3047, -0.4887, -1.0534, -0.3291]])


##  Bài 8. Autograd cơ bản

In [10]:
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [11]:
x = torch.tensor(3.6, requires_grad=True)

y = 3*x**2 + 2*x + 1

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


## Bài 9. Gradient Descent tìm hệ số đa thức

In [16]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[0.4485],
        [0.0330],
        [1.4503]], requires_grad=True)
Learned coefficients:
tensor([[1.0136],
        [1.9404],
        [2.5251]], requires_grad=True)


## Bài 10. Giải hệ phương trình bằng Autograd

In [13]:
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.2010, requires_grad=True)
B = tensor(4.7990, requires_grad=True)
C = tensor(3.7990, requires_grad=True)
D = tensor(2.7990, requires_grad=True)


## Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:
* Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.
* Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.
* Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.
* Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [14]:
import torch

print("--- YÊU CẦU 1 ---")
X = torch.arange(24)
X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("Kích thước 4x6:\n", X_4x6)
print("Kích thước 2x12:\n", X_2x12)
print("Kích thước 2x3x4:\n", X_2x3x4)

print("\n--- YÊU CẦU 2 ---")
torch.manual_seed(42)
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("Tensor A:\n", A)
print("Tensor B:\n", B)
print("A + B:\n", A + B)
print("A * B (Element-wise):\n", A * B)
print("A / B (Element-wise):\n", A / B)

print("Trung bình theo cột của A:", torch.mean(A, dim=0))
print("Độ lệch chuẩn theo cột của A:", torch.std(A, dim=0))

print("\n--- YÊU CẦU 3 ---")
x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()

print("Tính bằng PyTorch autograd (dy/dx tại x=2):", x.grad.item())

print("\n--- YÊU CẦU 4 ---")
np_x = torch.randn(100, 1) * 5
y_true = 2 * (np_x ** 2) - 3 * np_x + 5

XX = torch.cat([np_x**2, np_x, torch.ones_like(np_x)], dim=1)

w = torch.randn(3, 1, requires_grad=True)
optimizer = torch.optim.NAdam([w], lr=0.01)

for epoch in range(2000):
    optimizer.zero_grad()
    y_pred = XX @ w
    mse = torch.mean((y_true - y_pred) ** 2)
    mse.backward()
    optimizer.step()

learned_w = w.detach().numpy().ravel()
print(f"Hệ số tìm được (a, b, c): a = {learned_w[0]:.2f}, b = {learned_w[1]:.2f}, c = {learned_w[2]:.2f}")
print("Hệ số lý thuyết ban đầu : a = 2.00, b = -3.00, c = 5.00")

--- YÊU CẦU 1 ---
Kích thước 4x6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
Kích thước 2x12:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
Kích thước 2x3x4:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

--- YÊU CẦU 2 ---
Tensor A:
 tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
Tensor B:
 tensor([[ 1.1103, -1.6898, -0.9890,  0.9580],
        [ 1.3221,  0.8172, -0.7658, -0.7506],
        [ 1.3525,  0.6863, -0.3278,  0.7950]])
A + B:
 tensor([[ 1.4470, -1.5610, -0.7545,  1.1883],
        [ 0.1993,  0.6309,  1.4424, -1.3886],
        [ 1.8142,  0.9537,  0.2071,  1.6043]])
A * B (Element-wise):
 tensor([[ 0.3738, -